//! Japanese dictionary (English text -> Japanese).

pub const ENTRIES: &[(&str, &str)] = &[
    ("Reserved", "予約済み"),
    ("Favorites", "お気に入り"),
    ("Personal time", "個人時間"),
    ("No results.", "該当なし。"),
    (
        "Synced {n} sessions ({changed} changed, {removed} removed). Catalog version {version}.",
        "{n} 件のセッションを同期しました（変更 {changed} 件、削除 {removed} 件）。カタログ版: {version}",
    ),
    ("Not signed in. Run `riv login`.", "サインインしていません。`riv login` を実行してください。"),
    ("Signed in.", "サインインしました。"),
    ("Signed out.", "サインアウトしました。"),
    ("Open this URL in your browser to sign in:", "ブラウザで次の URL を開いてサインインしてください:"),
    ("Nothing is scheduled.", "予定はありません。"),
    ("unknown", "不明"),
    (
        "Opening the sign-out page; if the browser does not open, visit:",
        "サインアウトのページを開きます。ブラウザが開かない場合は次の URL を開いてください:",
    ),
    ("Browser sessions cleared.", "ブラウザ側のセッションを終了しました。"),
    (
        "Your browser may still be signed in to Builder ID. To switch accounts run `riv logout --browser` or `riv login --switch-account`.",
        "ブラウザが Builder ID にサインインしたままの可能性があります。アカウントを切り替えるには `riv logout --browser` か `riv login --switch-account` を実行してください。",
    ),
    ("1/3 What do you want from re:Invent this year (purpose)?", "1/3 今年の re:Invent で何を得たいですか（目的）？"),
    ("2/3 Which topics/services interest you?", "2/3 興味のあるトピック・サービスは？"),
    (
        "3/3 Constraints (days off, travel time, must-attend events)?",
        "3/3 制約は？（空けておく日、移動時間、必ず出る予定など）",
    ),
    ("kept existing", "既存のファイルを保持:"),
    ("created", "作成:"),
    ("TBD", "未定"),
    ("walk {n} min · leave by {time}", "徒歩 {n} 分・{time} までに出る"),
    ("walk: unknown", "徒歩: 不明"),
    ("Nothing scheduled on this day.", "この日の予定はありません。"),
    ("prep note available", "予習ノートあり"),
    ("+{n} more", "ほか {n} 件"),
    ("Time", "時刻"),
    ("Session", "セッション"),
    ("Where", "場所"),
    ("Walk", "移動"),
    ("In 3 lines", "3行で"),
    ("Last year's version", "昨年版"),
    ("What changed", "変更点"),
    ("Terms to know", "用語"),
    ("Questions to ask", "聞くべき問い"),
    ("Related sessions", "関連"),
    ("Stopped:", "中断:"),
    (
        "Some outcomes are unknown. Reconcile and resend only what is missing: riv apply --resume {run}",
        "結果が不明な操作があります。照合して不足分だけ再送します: riv apply --resume {run}",
    ),
    ("Verify: your schedule matches the spec.", "照合: スケジュールは spec と一致しています。"),
    ("Verify: differences remain:", "照合: 差分が残っています:"),
    ("This file is generated by riv. Do not edit.", "このファイルは riv が生成します。編集しないでください。"),
    ("Favorite", "お気に入り"),
    ("Pending:", "未反映:"),
    ("Block", "個人時間"),
    ("No changes. Your schedule already matches the spec.", "変更はありません。スケジュールは spec と一致しています。"),
    ("Alternatives for", "代替候補:"),
    ("warning:", "警告:"),
    (
        "Plan: {res} to reserve, {rep} to replace, {can} to cancel, {fav} to favorite, {unf} to unfavorite, {blk} block changes.",
        "計画: 予約 {res} / 置換 {rep} / 取消 {can} / お気に入り {fav} / 解除 {unf} / 個人時間 {blk}",
    ),
    (
        "A replace cancels first; if the new session is full you may lose the seat. Apply requires {flags}.",
        "置換は先に取り消すため、新しいセッションが満席だと今の席を失う可能性があります。適用には {flags} が必要です。",
    ),
    ("To apply: riv apply --plan {id}{flags}", "適用するには: riv apply --plan {id}{flags}"),
];

pub fn lookup(key: &str) -> Option<&'static str> {
    ENTRIES.iter().find(|(k, _)| *k == key).map(|(_, v)| *v)
}
