//! Japanese dictionary (English text -> Japanese).

pub const ENTRIES: &[(&str, &str)] = &[
    ("Reserved", "予約済み"),
    ("Favorites", "お気に入り"),
    ("Personal time", "個人時間"),
    ("No results.", "該当なし。"),
    (
        "Synced {n} sessions ({changed} changed, {removed} removed). Catalog version {version}.",
        "{n} 件のセッションを同期しました（変更 {changed} 件、削除 {removed} 件）。カタログ版: {version}",
    ),
    ("Not signed in. Run `riv login`.", "サインインしていません。`riv login` を実行してください。"),
    ("Signed in.", "サインインしました。"),
    ("Signed out.", "サインアウトしました。"),
    ("Open this URL in your browser to sign in:", "ブラウザで次の URL を開いてサインインしてください:"),
    ("Nothing is scheduled.", "予定はありません。"),
    ("unknown", "不明"),
    ("Stopped:", "中断:"),
    (
        "Some outcomes are unknown. Reconcile and resend only what is missing: riv apply --resume {run}",
        "結果が不明な操作があります。照合して不足分だけ再送します: riv apply --resume {run}",
    ),
    ("Verify: your schedule matches the spec.", "照合: スケジュールは spec と一致しています。"),
    ("Verify: differences remain:", "照合: 差分が残っています:"),
    ("This file is generated by riv. Do not edit.", "このファイルは riv が生成します。編集しないでください。"),
    ("Favorite", "お気に入り"),
    ("Pending:", "未反映:"),
    ("Block", "個人時間"),
    ("No changes. Your schedule already matches the spec.", "変更はありません。スケジュールは spec と一致しています。"),
    ("Alternatives for", "代替候補:"),
    ("warning:", "警告:"),
    (
        "Plan: {res} to reserve, {rep} to replace, {can} to cancel, {fav} to favorite, {unf} to unfavorite, {blk} block changes.",
        "計画: 予約 {res} / 置換 {rep} / 取消 {can} / お気に入り {fav} / 解除 {unf} / 個人時間 {blk}",
    ),
    (
        "A replace cancels first; if the new session is full you may lose the seat. Apply requires {flags}.",
        "置換は先に取り消すため、新しいセッションが満席だと今の席を失う可能性があります。適用には {flags} が必要です。",
    ),
    ("To apply: riv apply --plan {id}{flags}", "適用するには: riv apply --plan {id}{flags}"),
];

pub fn lookup(key: &str) -> Option<&'static str> {
    ENTRIES.iter().find(|(k, _)| *k == key).map(|(_, v)| *v)
}
