//! `tasks.md`: a display-only checklist regenerated after every apply.

use super::{ActionStatus, Outcome};
use crate::api::Schedule;
use crate::desired::{Desired, Want};
use crate::format::start_local;
use crate::i18n::{Lang, t_in};
use crate::plan::CatalogView;
use std::collections::BTreeMap;

pub const BANNER: &str = "This file is generated by riv. Do not edit.";

pub fn render_tasks(d: &Desired, s: &Schedule, cat: &dyn CatalogView, outcomes: &[Outcome], lang: Lang) -> String {
    let t = |k: &str| t_in(lang, k);
    // date key (local) -> lines, sorted by start time via the key prefix
    let mut days: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();
    let mut push = |sid: &str, text: String| {
        let (day, sort) = match cat.session(sid).and_then(|x| x.range_utc(cat.tz())) {
            Some((st, _)) => {
                let l = crate::timeutil::to_local(st, cat.tz());
                (l.format("%Y-%m-%d (%a)").to_string(), l.format("%H:%M").to_string())
            }
            None => ("(no date)".to_string(), "99:99".to_string()),
        };
        days.entry(day).or_default().push((sort, text));
    };
    let place = |sid: &str| -> String {
        match cat.session(sid) {
            Some(x) => {
                let at = [start_local(&x, cat.tz()), x.venue.clone().unwrap_or_default()];
                let at: Vec<&str> = at.iter().map(String::as_str).filter(|p| !p.is_empty()).collect();
                format!("{} ({})", x.code(), at.join(" "))
            }
            None => sid.to_string(),
        }
    };
    for ds in d.sessions.iter().filter(|x| x.want != Want::None) {
        let failed = outcomes.iter().find(|o| {
            o.target == ds.id
                && matches!(o.status, ActionStatus::Failed | ActionStatus::Unknown | ActionStatus::Skipped)
        });
        let reserved = s.reserved.contains(&ds.id);
        let favorite = s.favorites.contains(&ds.id);
        let code = cat.session(&ds.id).map(|x| x.code().to_string()).unwrap_or_else(|| ds.id.clone());
        let line = match (ds.want, failed) {
            (_, Some(o)) if o.status == ActionStatus::Unknown => {
                format!("- [ ] UNKNOWN: {code} {}", o.detail.clone().unwrap_or_default())
            }
            (_, Some(o)) if o.status == ActionStatus::Failed => {
                format!("- [ ] FAILED: {code} {}", o.detail.clone().unwrap_or_default())
            }
            (Want::Reserved, _) if reserved => format!("- [x] {} {}", t("Reserved"), place(&ds.id)),
            (Want::Favorite, _) if favorite || reserved => format!("- [x] {} {}", t("Favorite"), place(&ds.id)),
            _ => format!("- [ ] {} {}", t("Pending:"), place(&ds.id)),
        };
        push(&ds.id, line.trim_end().to_string());
    }
    let mut out = format!("{}\n\n", t(BANNER));
    for (day, mut lines) in days {
        lines.sort();
        out.push_str(&format!("## {day}\n"));
        for (_, l) in lines {
            out.push_str(&l);
            out.push('\n');
        }
        out.push('\n');
    }
    for b in &d.blocks {
        let done = s.personal_time.iter().any(|p| p.title == b.title);
        out.push_str(&format!("- [{}] {}: {} ({})\n", if done { "x" } else { " " }, t("Block"), b.title, b.start));
    }
    out
}
